from typing import Generic, Iterator, TypeVar

_T = TypeVar("_T")

class Collection(Generic[_T]):
    def __init__(self) -> None: ...
    def Add(self, item: _T) -> None: ...
    def __getitem__(self, index: int) -> _T: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __len__(self) -> int: ...
    @property
    def Items(self) -> "Collection[_T]": ...
