from typing import Any, TypeVar

_F = TypeVar("_F")

def AddReference(reference: str) -> None: ...
def FindAssembly(assmName: str) -> Any: ...
def GetClrType(typeName: str) -> type: ...
def ListAssemblies() -> list[str]: ...
def getPreload() -> bool: ...
def setPreload(preload: bool) -> None: ...
def clrmethod(method: _F) -> _F: ...
def clrproperty(prop: _F) -> _F: ...

__version__: str
