from typing import Generic, TypeVar

_K = TypeVar("_K")
_V = TypeVar("_V")

class Dictionary(Generic[_K, _V]):
    def __init__(self) -> None: ...
    def Add(self, key: _K, value: _V) -> None: ...
    def __getitem__(self, key: _K) -> _V: ...
    def __setitem__(self, key: _K, value: _V) -> None: ...
    def __contains__(self, key: _K) -> bool: ...
